### ISSUE TITLE
Game crashes 

### ISSUE THREAD

**Issue by Qwazori** [Rain-World-Modding/RegionKit#11]
During the save the game hangs and crashes , and you only have to restart it. After restarting, endless loading when opening a save in which there was a crash. After disabling the mod, everything works fine.

**Comment by thalber** [comment]
please attach log files (`rain world/exceptionlog.txt`, `rain world/bepinex/logoutput.log`) and give more information about the environment (other installed mods) to help identify the issue

**Comment by DryCryCrystal** [comment]
No logs sent, closing this as there is no way to fix this without them.
