### ISSUE TITLE
Monk - Going from SU to LF (Outskirts to Farm Arrays)

### ISSUE THREAD

**Issue by DanteAyagawe** [Rain-World-Modding/RegionKit#20]
It appears that whenever I try to go from Outskirts to Farm Arrays it bugs out and I can't open the map anymore, when hibernating, it freezes the game

Exception Log:
NullReferenceException: Object reference not set to an instance of an object
RegionKit.Modules.Misc.ExtendedGates.GateMarker_ctor (On.HUD.Map+GateMarker+orig_ctor orig, HUD.Map+GateMarker self, HUD.Map map, System.Int32 room, RegionGate+GateRequirement req, System.Boolean showAsOpen) (at <51de14e5461543c38031fad0a37d10c3>:0)
DMD<>?-298184448.Hook<HUD.Map+GateMarker::.ctor>?1313026048 (HUD.Map+GateMarker , HUD.Map , System.Int32 , RegionGate+GateRequirement , System.Boolean ) (at <638115e769ab4661b59720e76ce00960>:0)
DMD<_ctor>?-298184448._HUD_Map::_ctor (HUD.Map this, HUD.HUD hud, HUD.Map+MapData mapData) (at <feeb066ac4154c4a8b2ec97c94837f76>:0)
DMD<>?-298184448.Trampoline<HUD.Map::.ctor>?1736124928 (HUD.Map , HUD.HUD , HUD.Map+MapData ) (at <f143452ca2b146e29a50d4fda6af73cc>:0)
MapOptions.MapMod.HUD_Map_ctor (On.HUD.Map+orig_ctor orig, HUD.Map map, HUD.HUD hud, HUD.Map+MapData map_data) (at <9acc8a24393c449da9b8c2e1cf993f54>:0)
DMD<>?-298184448.Hook<HUD.Map::.ctor>?703698944 (HUD.Map , HUD.HUD , HUD.Map+MapData ) (at <2a36682f186142f3a8a75dc0b28edacf>:0)
HUD.HUD.ResetMap (HUD.Map+MapData mapData) (at <1014ff9a5d9941ab9e645d4f5c9384a5>:0)
OverWorld.WorldLoaded () (at <1014ff9a5d9941ab9e645d4f5c9384a5>:0)
DMD<Update>?-298184448._OverWorld::Update (OverWorld this) (at <5f1047ca1d2a4b78a927633fcd8fc5fd>:0)
DMD<>?-298184448.Trampoline<OverWorld::Update>?621393408 (OverWorld ) (at <722366d4a70b4d5e8781e6efff627f2e>:0)
WarpModMenu.OverWorld_Update (On.OverWorld+orig_Update orig, OverWorld self) (at <5084dd4e6d074ac6997973a6031d5ec7>:0)
DMD<>?-298184448.Hook<OverWorld::Update>?1629092864 (OverWorld ) (at <d2e3f8feb8e74131a130afb15fa9a5e3>:0)
RainWorldGame.Update () (at <1014ff9a5d9941ab9e645d4f5c9384a5>:0)
MainLoopProcess.RawUpdate (System.Single dt) (at <1014ff9a5d9941ab9e645d4f5c9384a5>:0)
DMD<RawUpdate>?-298184448._RainWorldGame::RawUpdate (RainWorldGame this, System.Single dt) (at <1a8e796eb59b4f79a281ea02e4e9bc65>:0)
DMD<>?-298184448.Trampoline<RainWorldGame::RawUpdate>?1967963648 (RainWorldGame , System.Single ) (at <dddbd9f77b51412a93a77b96bc1761c2>:0)
Pom.Pom.RainWorldGameRawUpdate (On.RainWorldGame+orig_RawUpdate orig, RainWorldGame self, System.Single dt) (at <8f33d22530bb42aca0a8d6a792a4f26c>:0)
DMD<>?-298184448.Hook<RainWorldGame::RawUpdate>?-456811520 (RainWorldGame , System.Single ) (at <c4dad825c29f4c80a1a10231a22d8eda>:0)
ProcessManager.Update (System.Single deltaTime) (at <1014ff9a5d9941ab9e645d4f5c9384a5>:0)
RainWorld.Update () (at <1014ff9a5d9941ab9e645d4f5c9384a5>:0)

At the console log it just keeps repeating this lines:
NEXT PROCESS COMMUNICATION
savKarma: 10
next screen MAP KARMA: 10
NEXT PROCESS COMMUNICATION
savKarma: 10
next screen MAP KARMA: 10
NEXT PROCESS COMMUNICATION

**Comment by DanteAyagawe** [comment]
I'll try just using region kit

**Comment by DanteAyagawe** [comment]
Tried loading the saved game, freezes it

**Comment by DanteAyagawe** [comment]
Still bugs out, hope these datas collected helps out

**Comment by DryCryCrystal** [comment]
Appears to be the same issue as #18
