### ISSUE TITLE
background is no longer displayed when reloading the region.

### ISSUE THREAD

**Issue by LaVADraGoN** [Rain-World-Modding/RegionKit#28]
If I set a background and save it, reload the save. The background dont load automaticly if entered the map again.
It need to manually load the image to be displayed again. The settings for the background are saved in the files.
Do i miss something? I cant get the background to work permanetly on the level.

**Comment by Bro748** [comment]
Apologies for the late response, but you need to add the AboveCloudsView room effect to the room.
