### ISSUE TITLE
RegionKit crashing game on startup

### ISSUE THREAD

**Issue by BouncyBonBon** [Rain-World-Modding/RegionKit#37]
I recently started having an issue with Rain World after adding a few mods where when I applied the mods the game would be unable to startup again. after slowly going through all the mods disabling and re-enabling them all I found the issue in RegionKit, I have no clue what is causing the issue as I am on steam and therefore don't have any of the crash logs BepInEx provides.

**Comment by BouncyBonBon** [comment]
Oh hang on I found the logOutput, let me see if I can crash myself again for the log

**Comment by BouncyBonBon** [comment]
[LogOutput.log](https://github.com/Rain-World-Modding/RegionKit/files/12214207/LogOutput.log)
Here's the LogOutput, I can't read it so I hope someone here can

**Comment by thalber** [comment]
This log is empty, try consolelog.txt and exceptionlog.txt from the game's main folder

**Comment by BouncyBonBon** [comment]
[consoleLog.txt](https://github.com/Rain-World-Modding/RegionKit/files/12214884/consoleLog.txt)
[exceptionLog.txt](https://github.com/Rain-World-Modding/RegionKit/files/12214885/exceptionLog.txt)
these?

**Comment by BouncyBonBon** [comment]
oh wait those are logs from not having regionkit on 1 sec

**Comment by BouncyBonBon** [comment]
[consoleLog.txt](https://github.com/Rain-World-Modding/RegionKit/files/12214904/consoleLog.txt)
ok i applied at and the exceptionLog disappeared but here's the console log of the crashes

**Comment by thalber** [comment]
nothing in this log either. if the game is frozen and logs stop with no errors logged, the issue is probably that it gets stuck in an infinite loop somewhere, but i'm not sure how i'd track where it happens

**Comment by thalber** [comment]
i suggest turning mods one by one to try narrow down the exact combination that causes the issue for now

**Comment by BouncyBonBon** [comment]
I already did that, it is clearly RegionKit causing the error

**Comment by BouncyBonBon** [comment]
it even crashes with exclusively RegionKit (and POM cause thats a dependency)

**Comment by thalber** [comment]
it doesn't happen for me so it's likely a combination of regionkit and something else? according to your logoutput you have some other mods enabled

**Comment by BouncyBonBon** [comment]
yes I did

**Comment by thalber** [comment]
Sometimes mysterious crashes can be solved by wiping the bepinex folder and re-verifying game files

**Comment by BouncyBonBon** [comment]
does BepInEx clash with the steam workshop?

**Comment by BouncyBonBon** [comment]
oh i was too scared to wipe the BepInEx as i thought it might brick the game

**Comment by thalber** [comment]
> oh i was too scared to wipe the BepInEx as i thought it might brick the game

bepinex files are tracked along with the game itself so they'll be restored when you verify integrity

**Comment by BouncyBonBon** [comment]
yeah no that didnt fix it :/

**Comment by BouncyBonBon** [comment]
should I also remove the BOI folder?

**Comment by BouncyBonBon** [comment]
when i removed it it broke the game oh well

**Comment by BouncyBonBon** [comment]
ill just play without RK
