### ISSUE TITLE
Placed Wind Removes all objects in room

### ISSUE THREAD

**Issue by WTheFool83** [Rain-World-Modding/RegionKit#67]
When I save and go back to see if my things are working all of the objects that were placed just disappear. It did the same in vanilla rooms too. Not quite sure what is causing this other than my odd amalgamation of mods. Sorry for the trouble.

**Comment by Bro748** [comment]
This is a known issue btw and it's fixed on my branch. Will be fixed in the next update.

**Comment by WTheFool83** [comment]
thank you :)

**Comment by DryCryCrystal** [comment]
Appears to be fixed in 3.14.4
