### ISSUE TITLE
most recent version has a trojan

### ISSUE THREAD

**Issue by gitprobelms** [Rain-World-Modding/RegionKit#80]
please deal with this

**Comment by gitprobelms** [comment]
or windows may be having a fit but i am not going to download this until clarified

**Comment by DryCryCrystal** [comment]
I don't know if you fixed it or not, but I had a check on virus total and I'm not getting anything there that marks it as malicious.

https://www.virustotal.com/gui/url/3ac688ba3aac5ffc4bcf02830fba63901abfb46d6da18495c93a7d28074fff62/detection
https://www.virustotal.com/gui/file/fd04e4e85cfb957d6349a6ba898cfb7470678f14617534fd3cdb69e7028ca17a/detection

**Comment by gitprobelms** [comment]
Yes yes It was very late at night and my computer was having a fit for no reason sorry for the inconvenience
