### ISSUE TITLE
During sunset the background instantly snaps from the AtmosphereColor to the game's default blue.

### ISSUE THREAD

**Issue by AprilAprill** [Rain-World-Modding/RegionKit#87]
this was happening on both 3.14 and 3.15
https://github.com/Rain-World-Modding/RegionKit/assets/99157860/7122d090-4d58-451b-97a7-6cd3e4be9e11
here is the background file:
[AtC_RE_CCPebbs.txt](https://github.com/Rain-World-Modding/RegionKit/files/15358937/AtC_RE_CCPebbs.txt)

**Comment by Bro748** [comment]
Fixed with [Regionkit 3.15.1](https://github.com/Rain-World-Modding/RegionKit/releases/tag/3.15.1)
I also added options to change the atmosphereColor and multiplyColor for dusk and night
